all:
	make -C ./GNU_ARM_v7.2.1_Debug all

# Other Targets
clean:
	make -C ./GNU_ARM_v7.2.1_Debug clean

clean_all:
	make -C ./GNU_ARM_v7.2.1_Debug clean_all

.PHONY: all clean clean_all dependents
.SECONDARY: