/******************************************************************************
 *
 * @file   sl_btmesh_dcd.h
 * @brief  BLE Mesh element indexes and the maximum number of elements, models
 *         and provisioning bearers
 *
 *  Autogenerated file, do not edit
 *
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
// *INDENT-OFF*

#ifndef SL_BTMESH_DCD_H
#define SL_BTMESH_DCD_H

// Defines the maximum number of elements the application needs based on the
// btmeshconf and dcd files.
#define SL_BTMESH_CONFIG_MAX_ELEMENTS 1

// Defines the maximum number of models the application needs based on the
// btmeshconf and dcd files.
#define SL_BTMESH_CONFIG_MAX_MODELS 3


#endif // SL_BTMESH_DCD_H